ChautariNews/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls',namespace='pages')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import home,about,services,contacts,country,economic,politics,science,startup


app_name = 'pages'

urlpatterns = [
	path('',home,name='home'),
	path('about/',about,name='about'),
	path('servies/',services,name='services'),
	path('contacts/',contacts,name='contacts'),
	path('country/',country,name='country'),
	path('economic/',economic,name='economic'),
	path('politics/',politics,name='politics'),
	path('science/',science,name='science'),
	path('startup/',startup,name='startup'),

]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render

# Create your views here.

def home(request):

	return render(request,'home.html')


def about(request):

	return render(request,'about.html')

def services(request):

	return render(request,'services.html')

def contacts(request):

	return render(request,'contacts.html')

def country(request):

	return render(request,'country.html')

def economic(request):

	return render(request,'economic.html')

def politics(request):

	return render(request,'politics.html')

def startup(request):

	return render(request,'startup.html')

def science(request):

	return render(request,'science.html')

pages/templates/about.html
{% extends 'base.html'%}
{% block content %}
 <h3>about page </h3>
{% endblock %}

pages/templates/contacts.html
{% extends 'base.html'%}

{% block content %}

	<h1> contact info here </h1>

{% endblock %}

pages/templates/country.html
{% extends 'base.html' %}

{% block content %}
	<h2>hello from country of lord buddha </h2>

{% endblock %}

pages/templates/economic.html
{% extends 'base.html' %}
{% block content %}

	<h2> economy section </h2>
{% endblock %}

pages/templates/politics.html
{% extends 'base.html'%}

{% block content %}

	<h3> politics section </h3>

{% endblock %}

pages/templates/science.html
{% extends 'base.html' %}

{% block content %}

	<h2>hello sci-fi</h2>

{% endblock %}

pages/templates/services.html
{% extends 'base.html'%}
{% block content %}
<h1>hello i am service</h1>

{% endblock %}

pages/templates/startup.html
{% extends 'base.html' %}

{% block content %}
	<h2>hello startup for enterpreneurship</h2>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- font awesome icon -->
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
	<!-- style.css for navbar -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>
		{% block title %}
		
		{% endblock %}
	</title>
</head>
<body id ="main">
	<!-- top bar -->
	{% include 'partials/_topbar.html' %}
	<!-- nav bar -->
	{% include 'partials/_navbar.html' %}

	<!-- main contents -->
	{% block content %}

	{% endblock %}

	<!-- footer -->
	{% include 'partials/_footer.html' %}

	<!-- navbar js -->
	<script type="text/javascript" src="{% static 'js/resnav.js' %}"></script>
</body>
</html>

templates/partials/_footer.html
 <div class="wrapper">
 	<footer>
    	<p>SMG &copy; 2020</p>
  	</footer>
</div>

templates/partials/_navbar.html
<div class="wrapper">
        <!-- Navigation -->
        <!-- svg navbar -->
        <span class="svgnav" >
            <a href="#" onclick="openSlideMenu()">
                <svg width="30" height="30">
                    <path d="M0,5 30,5" stroke="#fff"
                    stroke-width="5"/>
                    <path d="M0,14 30,14" stroke="#fff"
                    stroke-width="5"/>
                    <path d="M0,23 30,23" stroke="#fff"
                    stroke-width="5"/>
                </svg>
            </a>
        </span>
        <nav class="main-nav">
            <ul>
                <li><a href="{% url 'pages:home' %}">गृह पृष्ठ</a></li>
                <li><a href="{% url 'pages:about' %}">About</a></li>
                <li><a href="{% url 'pages:services' %}">Services</a></li>
                <li><a href="{% url 'pages:contacts' %}">Contacts</a></li>
                <li><a href="{% url 'pages:country' %}">देश</a></li>
                <li><a href="{% url 'pages:economic' %}">अर्थ</a></li>
                <li><a href="{% url 'pages:politics' %}">राजनिति</a></li>
                <li><a href="{% url 'pages:science' %}">बिज्ञान</a></li>
                <li><a href="{% url 'pages:startup' %}">स्टार्टअप</a></li>
            </ul>
            
        </nav>
        <!-- side-navbar -->
        <div id="side-menu" class="side-nav">
            <a href="#" class="btn-close" onclick="closeSlideMenu()">&times;</a>
            <a href="{% url 'pages:home' %}">Home</a>
            <a href="{% url 'pages:about' %}">About</a>
            <a href="#">Services</a>
            <a href="#">Contacts</a>
            <a href="#">देश</a>
            <a href="#">अर्थ</a>
            <a href="#">राजनिति</a>
            <a href="#">बिज्ञान</a>
            <a href="#">स्टार्टअप</a>

        </div>

</div>

templates/partials/_topbar.html
<h2> i am topbar </h2>